package com.example.demo.db.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tag_url
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class TagUrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_url.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_url.tag_id
     *
     * @mbggenerated
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_url.url_id
     *
     * @mbggenerated
     */
    private Integer urlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_url.id
     *
     * @return the value of tag_url.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_url.id
     *
     * @param id the value for tag_url.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_url.tag_id
     *
     * @return the value of tag_url.tag_id
     *
     * @mbggenerated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_url.tag_id
     *
     * @param tagId the value for tag_url.tag_id
     *
     * @mbggenerated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_url.url_id
     *
     * @return the value of tag_url.url_id
     *
     * @mbggenerated
     */
    public Integer getUrlId() {
        return urlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_url.url_id
     *
     * @param urlId the value for tag_url.url_id
     *
     * @mbggenerated
     */
    public void setUrlId(Integer urlId) {
        this.urlId = urlId;
    }
}