package com.example.demo.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table url
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Url {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column url.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.id
     *
     * @return the value of url.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.id
     *
     * @param id the value for url.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column url.url
     *
     * @return the value of url.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column url.url
     *
     * @param url the value for url.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}