package com.example.demo.dao;

import com.example.demo.model.TagUrl;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TagUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_url
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_url
     *
     * @mbggenerated
     */
    int insert(TagUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_url
     *
     * @mbggenerated
     */
    TagUrl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_url
     *
     * @mbggenerated
     */
    List<TagUrl> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_url
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TagUrl record);
}